### ISSUE TITLE
SMTP Credentials

### ISSUE THREAD

**Issue by RigoTheCEO** [MattPettitZA/Python-Work#1]
Please don't upload your SMTP credentials to GitHub. That's how you get hacked. Use a .env file or something. Even though you removed it, it still shows up on previous commits. I suggest you delete this repository & create a new one.

https://github.com/MattPettitZA/Python-Work/blob/b64edc6ce707b15cf56b4d5a7765a58f887a6e0a/Mail%20sender.py#L11

**Comment by RigoTheCEO** [comment]
& change your password.

**Comment by MattPettitZA** [comment]
Thanks, I removed it soon after uploading it, I changed my password soon after.
